### ISSUE TITLE
XibarCovid une application pour traquer en temps réels le covid 19 au Sénégal et à travers le monde.

### ISSUE THREAD

**Issue by Mohamed-Sarr** [OpenCOVID19-Senegal/Comment-Contribuer#2]
https://github.com/Mohamedeveloppeur/XibarCovid

**Comment by dofbi** [comment]
Hello @Mohamedeveloppeur nice apps
Je t'es lancé une invite à nous rejoindre
Merci pour ta contribution

**Comment by Mohamed-Sarr** [comment]
merci


Le lun. 20 avr. 2020 à 21:31, Mamadou Diagne <notifications@github.com> a
écrit :
